# Generated by Django 4.1.4 on 2023-05-20 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="price",
        ),
    ]
